server:
  port: 9151

  #应用的名称，可选


spring:
  application:
    name: hotelManagerApi

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/homestay?serverTimezone=GMT
      username: root
      password: 123456

      max-active: 20
      max-wait: 2500
      connection-error-retry-attempts: 0
      fail-fast: true
      break-after-acquire-failure: true

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.rabbiter.hotel.domain
  global-config:
    db-config:
      id-type: auto
    banner: false


